// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type File struct {
	ID              string        `json:"id"`
	Filename        string        `json:"filename"`
	Owner           *User         `json:"owner"`
	SizeBytes       int           `json:"sizeBytes"`
	MimeType        string        `json:"mimeType"`
	UploadedAt      string        `json:"uploadedAt"`
	IsPublic        bool          `json:"isPublic"`
	PublicShareLink *string       `json:"publicShareLink,omitempty"`
	DownloadCount   int           `json:"downloadCount"`
	Storage         *StorageStats `json:"storage"`
}

type FileFilterInput struct {
	Filename  *string `json:"filename,omitempty"`
	MimeType  *string `json:"mimeType,omitempty"`
	MinSize   *int    `json:"minSize,omitempty"`
	MaxSize   *int    `json:"maxSize,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
}

type Folder struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Owner    *User     `json:"owner"`
	Parent   *Folder   `json:"parent,omitempty"`
	Children []*Folder `json:"children"`
	Files    []*File   `json:"files"`
}

type Mutation struct {
}

type NewFolderInput struct {
	Name           string  `json:"name"`
	ParentFolderID *string `json:"parentFolderId,omitempty"`
}

type Query struct {
}

type StorageStats struct {
	OriginalSizeBytes     int     `json:"originalSizeBytes"`
	DeduplicatedSizeBytes int     `json:"deduplicatedSizeBytes"`
	SavedBytes            int     `json:"savedBytes"`
	SavedPercentage       float64 `json:"savedPercentage"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
